# Generated by Django 2.0.4 on 2018-06-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositsAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('currency', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('fund_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_extra', models.CharField(blank=True, max_length=255, null=True)),
                ('txid', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('aasm_state', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('confirmations', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_transaction_id', models.IntegerField(blank=True, null=True)),
                ('txout', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
