# Generated by Django 2.0.7 on 2018-08-23 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_manage', '0005_walletrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coin_account', '0002_auto_20180822_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WithdrawHistroy',
            new_name='WithdrawHistory',
        ),
        migrations.AddField(
            model_name='withdrawreason',
            name='reason_type',
            field=models.CharField(default='HOT', max_length=30),
        ),
    ]
