# Generated by Django 2.0.7 on 2018-08-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_account', '0003_auto_20180823_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawapply',
            name='deposit_volume',
        ),
        migrations.RemoveField(
            model_name='withdrawapply',
            name='status',
        ),
    ]
