# Generated by Django 2.0.7 on 2018-08-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_account', '0004_auto_20180825_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawapply',
            name='supervisor',
            field=models.BigIntegerField(blank=True, default=-1, null=True),
        ),
    ]
