# Generated by Django 2.0.7 on 2018-08-27 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coin_account', '0006_withdrawapply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawhistory',
            name='requester',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='requester_info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
