# Generated by Django 2.0.7 on 2018-08-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_account', '0007_withdrawhistory_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawhistory',
            name='txid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
