# Generated by Django 2.0.7 on 2018-08-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_account', '0009_withdrawhistory_withdraw_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawhistory',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
