# Generated by Django 2.1.3 on 2018-12-14 09:23

from django.db import migrations
from bcoffice.migrate_init_value import CoinAccount

def load_stores(apps, schema_editor):
    WithdrawReason = apps.get_model('coin_account', 'WithdrawReason')
    if (WithdrawReason.objects.all()).exists() is False:
        for index, item in enumerate(CoinAccount.DEFAULT_WITHDRAW_REASON):
            instance_reason = WithdrawReason.objects.create(
                id=index+1,
                code=item['code'],
                description=item['description'],
                reason_type=item['reason_type']
            )

class Migration(migrations.Migration):

    dependencies = [
        ('coin_account', '0010_auto_20180829_1615'),
    ]

    operations = [
        migrations.RunPython(load_stores)
    ]
