# Generated by Django 2.0.4 on 2018-06-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlarm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alarm_code', models.CharField(max_length=5, unique=True)),
                ('is_sms', models.BooleanField(default=False)),
                ('is_email', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'system_alarm',
            },
        ),
    ]
