# Generated by Django 2.0.7 on 2018-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_manage', '0002_depositaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaddress',
            name='address_type',
            field=models.CharField(default='INSIDE', max_length=20),
        ),
    ]
