# Generated by Django 2.0.7 on 2018-07-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_manage', '0003_auto_20180712_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaddress',
            name='wallet_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
