# Generated by Django 2.1.3 on 2018-12-14 09:23

from datetime import datetime
from django.db import migrations
from django.contrib.auth.hashers import make_password
from bcoffice.migrate_init_value import PolicyManage

def load_stores(apps, schema_editor):
    SystemAlarm = apps.get_model('policy_manage', 'SystemAlarm')
    if (SystemAlarm.objects.all()).exists() is False:
        for item in PolicyManage.DEFAULT_SYSTEM_ALARM:
            instance_system_alarm = SystemAlarm.objects.create(
                alarm_code=item['alarm_code'],
                is_sms=item['is_sms'],
                is_email=item['is_email']
            )

class Migration(migrations.Migration):

    dependencies = [
        ('policy_manage', '0005_walletrule'),
    ]

    operations = [
        migrations.RunPython(load_stores)
    ]
