# Generated by Django 2.0.4 on 2018-05-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_ask', models.IntegerField(blank=True, null=True)),
                ('bid_bid', models.IntegerField(blank=True, null=True)),
                ('ask_bid', models.IntegerField(blank=True, null=True)),
                ('ask_ask', models.IntegerField(blank=True, null=True)),
                ('trd_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('trd_volume', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('trd_funds', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('trd_trend', models.IntegerField(blank=True, null=True)),
                ('trd_created_at', models.DateTimeField(blank=True, null=True)),
                ('bid_id', models.IntegerField(blank=True, null=True)),
                ('bid_member_id', models.IntegerField(blank=True, null=True)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('bid_origin_volume', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('trd_bid_fee', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('bid_created_at', models.DateTimeField(blank=True, null=True)),
                ('ask_id', models.IntegerField(blank=True, null=True)),
                ('ask_member_id', models.IntegerField(blank=True, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('ask_origin_volume', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('trd_ask_fee', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('ask_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
