# Generated by Django 2.0.7 on 2018-07-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_history', '0002_ordertotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_member_id', models.IntegerField(blank=True, null=True)),
                ('o_origin_id', models.IntegerField(blank=True, null=True)),
                ('o_first_id', models.IntegerField(blank=True, null=True)),
                ('t_id', models.IntegerField(blank=True, null=True)),
                ('o_state', models.IntegerField(blank=True, null=True)),
                ('o_bid', models.IntegerField(blank=True, null=True)),
                ('o_ask', models.IntegerField(blank=True, null=True)),
                ('o_currency', models.IntegerField(blank=True, null=True)),
                ('o_type', models.CharField(blank=True, max_length=8, null=True)),
                ('o_ord_type', models.CharField(blank=True, max_length=10, null=True)),
                ('o_source', models.CharField(max_length=255)),
                ('o_origin_volume', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('o_volume', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('o_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('s_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('t_bid_id', models.IntegerField(blank=True, null=True)),
                ('t_ask_id', models.IntegerField(blank=True, null=True)),
                ('t_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('t_volume', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('t_remain_volume', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('t_funds', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('t_bid_fee', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('t_ask_fee', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('s_created_at', models.DateTimeField(blank=True, null=True)),
                ('o_created_at', models.DateTimeField(blank=True, null=True)),
                ('t_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
