# Generated by Django 2.0.4 on 2018-04-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
    ]
