# Generated by Django 2.0.4 on 2018-04-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0002_auto_20180426_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
    ]
