# Generated by Django 2.0.4 on 2018-05-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0004_auto_20180503_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'support_questions_type',
            },
        ),
    ]
