# Generated by Django 2.0.4 on 2018-05-04 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0005_questiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_type', to='supports.QuestionType'),
            preserve_default=False,
        ),
    ]
