# Generated by Django 2.0.4 on 2018-05-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0006_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='contents',
            field=models.TextField(null=True),
        ),
    ]
