# Generated by Django 2.0.4 on 2018-05-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0007_auto_20180508_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
    ]
