# Generated by Django 2.0.4 on 2018-06-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0008_auto_20180509_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
