# Generated by Django 2.0.4 on 2018-06-25 04:56

from django.db import migrations, models
import django.db.models.deletion
import supports.models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0009_auto_20180615_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('files', models.FileField(blank=True, null=True, upload_to=supports.models.user_attach_path)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'boards_support_attach',
            },
        ),
        migrations.CreateModel(
            name='QuestionFileMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_question', to='supports.FileAttachment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attach_question', to='supports.Question')),
            ],
            options={
                'db_table': 'support_question_mapping',
            },
        ),
    ]
