# Generated by Django 2.0.4 on 2018-06-25 05:47

from django.db import migrations, models
import supports.models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0010_fileattachment_questionfilemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to=supports.models.user_attach_path),
        ),
    ]
