# Generated by Django 2.0.4 on 2018-06-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0011_auto_20180625_1447'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileattachment',
            table='support_attach',
        ),
    ]
