# Generated by Django 2.0.4 on 2018-06-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0012_auto_20180625_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRaw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('question_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('emp_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
