# Generated by Django 2.0.7 on 2018-07-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0013_questionraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionfilemap',
            name='file_info',
        ),
        migrations.RemoveField(
            model_name='questionfilemap',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuestionFileMap',
        ),
    ]
