# Generated by Django 2.0.7 on 2018-07-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0014_auto_20180705_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='locale',
            field=models.CharField(default='ko', max_length=20),
        ),
    ]
