# Generated by Django 2.0.7 on 2018-10-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0015_answer_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='category_id',
            field=models.BigIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiontype',
            name='lang',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
    ]
