# Generated by Django 2.1.3 on 2018-12-14 09:23

from django.db import migrations
from bcoffice.migrate_init_value import Supports

def load_stores(apps, schema_editor):
    QuestionType = apps.get_model('supports', 'QuestionType')
    if (QuestionType.objects.all()).exists() is False:
        for index, item in enumerate(Supports.DEFAULT_QUESTION_TYPE):
            instance_category = QuestionType.objects.create(
                id=index+1,
                type=item['type'],
                category_id=item['category_id'],
                lang=item['lang']
            )

class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0016_auto_20181023_0940'),
    ]

    operations = [
        migrations.RunPython(load_stores)
    ]
