# Generated by Django 2.0.7 on 2018-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0016_auto_20181023_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type_id',
            field=models.BigIntegerField(),
            preserve_default=False,
        ),
    ]
