# Generated by Django 2.0.4 on 2018-05-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managermemo',
            options={'ordering': ['-id']},
        ),
    ]
