# Generated by Django 2.0.7 on 2018-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MtsVer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mtsver',
            },
        ),
    ]
