# Generated by Django 2.0.7 on 2018-08-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_controls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MtsVer',
            new_name='MtsVersion',
        ),
        migrations.AlterModelTable(
            name='mtsversion',
            table='mts_version',
        ),
    ]
