# Generated by Django 2.0.7 on 2018-08-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_controls', '0002_auto_20180809_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtsversion',
            name='device',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
