# Generated by Django 2.0.7 on 2018-08-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_controls', '0003_auto_20180809_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtsversion',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
