# Generated by Django 2.0.7 on 2018-08-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_controls', '0004_mtsversion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtsversion',
            name='description',
        ),
    ]
