# Generated by Django 2.0.4 on 2018-05-04 07:29

import boards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('contents', models.TextField()),
                ('read_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'boards_faq_category',
            },
        ),
        migrations.CreateModel(
            name='FileAttach',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(blank=True, null=True, upload_to=boards.models.user_attach_path)),
                ('type', models.CharField(default='normal', max_length=50)),
            ],
            options={
                'db_table': 'boards_posts_attach',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='ing', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('read_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boards_posts',
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'boards_posts_type',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='posts_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.PostType'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileattach',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.Post'),
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.FaqCategory'),
        ),
        migrations.AddField(
            model_name='faq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
