# Generated by Django 2.0.4 on 2018-05-31 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_post_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileattach',
            old_name='url',
            new_name='files',
        ),
    ]
