# Generated by Django 2.0.4 on 2018-06-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20180614_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqlanguage',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='noticelanguage',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='postlanguage',
            old_name='board_id',
            new_name='board',
        ),
    ]
