# Generated by Django 2.0.4 on 2018-06-15 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20180615_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqlanguage',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_faq', to='boards.Faq'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='noticelanguage',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_notice', to='boards.Notice'),
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_post', to='boards.Post'),
        ),
    ]
