# Generated by Django 2.0.4 on 2018-06-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20180615_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='send',
            field=models.BooleanField(default=0),
        ),
    ]
