# Generated by Django 2.0.4 on 2018-06-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_notice_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.BooleanField(default=0),
        ),
    ]
