# Generated by Django 2.0.4 on 2018-06-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20180615_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileattachnotice',
            name='type',
        ),
    ]
