# Generated by Django 2.0.4 on 2018-06-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_remove_fileattachnotice_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqlanguage',
            old_name='language',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='noticelanguage',
            old_name='language',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='postlanguage',
            old_name='language',
            new_name='lang',
        ),
    ]
