# Generated by Django 2.0.4 on 2018-06-18 01:57

import boards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0012_auto_20180615_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='ing', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('soruce', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('read_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boards_daily',
            },
        ),
        migrations.CreateModel(
            name='DailyNewsLanguage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_daily', to='boards.DailyNews')),
            ],
            options={
                'db_table': 'boards_daily_language',
            },
        ),
        migrations.CreateModel(
            name='FileAttachDailyNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('files', models.FileField(blank=True, null=True, upload_to=boards.models.user_attach_path)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(default='normal', max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attach_daily', to='boards.DailyNews')),
            ],
            options={
                'db_table': 'boards_daily_attach',
            },
        ),
        migrations.RemoveField(
            model_name='fileattach',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posts_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postlanguage',
            name='board',
        ),
        migrations.DeleteModel(
            name='FileAttach',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostLanguage',
        ),
        migrations.DeleteModel(
            name='PostType',
        ),
    ]
