# Generated by Django 2.0.4 on 2018-06-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20180618_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailynews',
            old_name='soruce',
            new_name='source',
        ),
    ]
