# Generated by Django 2.0.4 on 2018-06-19 01:45

import boards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0014_auto_20180618_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinGuide',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='ing', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('developer', models.CharField(blank=True, max_length=100, null=True)),
                ('func', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('block_time', models.IntegerField(blank=True, null=True)),
                ('rewards', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boards_coinguide',
            },
        ),
        migrations.CreateModel(
            name='CoinGuideLanguage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_coinguide', to='boards.CoinGuide')),
            ],
            options={
                'db_table': 'boards_coinguide_language',
            },
        ),
        migrations.CreateModel(
            name='FileAttachCoinGuide',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('files', models.FileField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attach_coinguide', to='boards.DailyNews')),
            ],
            options={
                'db_table': 'boards_coinguide_attach',
            },
        ),
    ]
