# Generated by Django 2.0.4 on 2018-06-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_coinguide_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinguide',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
