# Generated by Django 2.0.4 on 2018-06-19 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_auto_20180619_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinGuideUsefulLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_coinguide', to='boards.CoinGuide')),
            ],
            options={
                'db_table': 'boards_coinguide_link',
            },
        ),
    ]
