# Generated by Django 2.0.4 on 2018-06-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_coinguideusefullink'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinguideusefullink',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
