# Generated by Django 2.0.4 on 2018-06-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0026_dailynewsfilemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeFileMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attach_notice', to='boards.Notice')),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_notice', to='boards.FileAttachment')),
            ],
            options={
                'db_table': 'boards_notice_mapping',
            },
        ),
        migrations.RemoveField(
            model_name='fileattachnotice',
            name='post',
        ),
        migrations.DeleteModel(
            name='FileAttachNotice',
        ),
    ]
