# Generated by Django 2.0.4 on 2018-06-21 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0030_auto_20180621_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynews',
            name='primary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_daily', to='boards.FileAttachment'),
        ),
    ]
