# Generated by Django 2.0.7 on 2018-07-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0033_auto_20180704_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinguide',
            name='currency',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
