# Generated by Django 2.0.7 on 2018-08-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0035_auto_20180705_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='send',
            new_name='send_email',
        ),
        migrations.AddField(
            model_name='notice',
            name='send_sms',
            field=models.BooleanField(default=0),
        ),
    ]
