# Generated by Django 2.0.7 on 2018-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0036_auto_20180814_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='category_id',
            field=models.BigIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='lang',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
    ]
