# Generated by Django 2.0.7 on 2018-10-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0037_auto_20181022_2048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faqcategory',
            unique_together={('category_id', 'lang')},
        ),
    ]
