# Generated by Django 2.0.7 on 2018-10-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0038_auto_20181023_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='faq_category',
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_category_id',
            field=models.BigIntegerField(),
            preserve_default=False,
        ),
    ]
