# Generated by Django 2.0.4 on 2018-04-05 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180404_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
