# Generated by Django 2.0.4 on 2018-06-11 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180611_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentduty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 11, 8, 19, 14, 785252, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departmentduty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 6, 11, 8, 19, 26, 184875, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departmentrank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 11, 8, 19, 31, 728675, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departmentrank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 6, 11, 8, 19, 37, 743592, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
