# Generated by Django 2.0.4 on 2018-06-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180611_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentduty',
            name='duty_eng_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='departmentrank',
            name='rank_eng_name',
            field=models.CharField(max_length=150),
        ),
    ]
