# Generated by Django 2.0.4 on 2018-06-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180612_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentduty',
            name='duty_eng_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='departmentrank',
            name='rank_eng_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
