# Generated by Django 2.0.4 on 2018-06-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180612_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttype',
            name='dept_eng_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
