# Generated by Django 2.0.4 on 2018-06-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_eng_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eng_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
