# Generated by Django 2.0.7 on 2018-08-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180620_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentduty',
            name='duty_cd',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='departmentrank',
            name='rank_cd',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='departmenttype',
            name='team_cd',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
