# Generated by Django 2.1.3 on 2018-12-13 17:07

from datetime import datetime
from django.db import migrations
from bcoffice.migrate_init_value import Account

def load_stores(apps, schema_editor):
    DepartmentDuty = apps.get_model('account', 'DepartmentDuty')
    if (DepartmentDuty.objects.all()).exists() is False:
        instance_duty = DepartmentDuty.objects.create(
            id=1,
            duty_cd=Account.DEFAULT_DEPT_DUTY['duty_cd'],
            duty_name=Account.DEFAULT_DEPT_DUTY['duty_name'],
            duty_eng_name=Account.DEFAULT_DEPT_DUTY['duty_eng_name'],
            status=Account.DEFAULT_DEPT_DUTY['status'],
            created_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            updated_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        )

    DepartmentRank = apps.get_model('account', 'DepartmentRank')
    if (DepartmentRank.objects.all()).exists() is False:
        instance_rank = DepartmentRank.objects.create(
            id=1,
            rank_cd=Account.DEFAULT_DEPT_RANK['rank_cd'],
            rank_name=Account.DEFAULT_DEPT_RANK['rank_name'],
            rank_eng_name=Account.DEFAULT_DEPT_RANK['rank_eng_name'],
            status=Account.DEFAULT_DEPT_RANK['status'],
            created_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            updated_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        )

    DepartmentType = apps.get_model('account', 'DepartmentType')
    if (DepartmentType.objects.all()).exists() is False:
        instance_type = DepartmentType.objects.create(
            id=1,
            dept_cd=Account.DEFAULT_DEPT_TYPE['dept_cd'],
            team_cd=Account.DEFAULT_DEPT_TYPE['team_cd'],
            dept_name=Account.DEFAULT_DEPT_TYPE['dept_name'],
            dept_eng_name=Account.DEFAULT_DEPT_TYPE['dept_eng_name'],
            managerial=Account.DEFAULT_DEPT_TYPE['managerial'],
            status=Account.DEFAULT_DEPT_TYPE['status'],
            created_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            updated_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        )

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20180828_1111'),
    ]

    operations = [
        migrations.RunPython(load_stores)
    ]
