# Generated by Django 2.1.3 on 2018-12-14 09:23

from datetime import datetime
from django.db import migrations
from django.contrib.auth.hashers import make_password
from bcoffice.migrate_init_value import Account

def load_stores(apps, schema_editor):
    User = apps.get_model('account', 'User')
    if (User.objects.all()).exists() is False:
        instance_user = User.objects.create(
            id=1,
            email=Account.DEFAULT_SUPER_USER['EMAIL'],
            password=make_password(Account.DEFAULT_SUPER_USER['PASSWORD']),
            cell_phone='010-0000-0000',
            name='administrator',
            eng_name='administrator',
            active=True,
            status='active',
            joined_date=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            close_date=None,
            created_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            updated_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        )

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_make_dept'),
    ]

    operations = [
        migrations.RunPython(load_stores)
    ]
