# Generated by Django 2.1.3 on 2018-12-14 09:50

from django.db import migrations

def load_stores(apps, schema_editor):
    Auth = apps.get_model('account', 'Auth')
    if (Auth.objects.all()).exists() is False:
        Auth.objects.create(id=1, user_id=1, role='ROLE_Super')

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_make_user'),
    ]

    operations = [
        migrations.RunPython(load_stores)
    ]
