# Generated by Django 2.0.4 on 2018-06-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_referral_id', models.IntegerField(blank=True, null=True)),
                ('r_member_id', models.IntegerField(blank=True, null=True)),
                ('f_created_at', models.DateTimeField(blank=True, null=True)),
                ('m_id', models.IntegerField(blank=True, null=True)),
                ('m_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('m_email', models.CharField(blank=True, max_length=255, null=True)),
                ('m_phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
